{
 "title": "OADP Prow Periodic",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influxdb_filter", "label": "filter" }
  ]
 },
 "panels": [
  {
   "title": "OADP CI Monitor",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# OADP Pull CI Dashboard\n# THIS IS STILL A WIP, validating data\n\n## Useful links\n* Search for errors:  https://search.ci.openshift.org/  \n* Test Grid: https://testgrid.k8s.io/redhat\n* OADP CI Config: https://github.com/openshift/release/tree/master/ci-operator/config/openshift/oadp-operator\n      \n## builds\n* upstream: https://app.travis-ci.com/github/openshift/oadp-operator\n* downstream: https://jenkins-cpaas-oadp.apps.cpaas-poc.r6c9.p1.openshiftapps.com/\n* internal cvp: https://jenkins-cvp-5d6ccd93bed8bd3809ddcb5d.apps.ocp-c1.prod.psi.redhat.com/view/Production%20Pipeline/job/cvp-product-test/"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Periodic OADP Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "OpenShift 4.9 Pass / Fail",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.8 Pass / Fail",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.8.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.8.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.8.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.7 Pass / Fail",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.6 Pass / Fail",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.6.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.6.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.6.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Periodic OADP Details by Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "OpenShift 4.9 AWS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*aws.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*aws.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*aws.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.9 GCP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*gcp.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*gcp.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*gcp.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.9 Azure",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*azure.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*azure.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*azure.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP -  OpenShift 4.9 AWS Periodic",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*aws.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP -  OpenShift 4.9 GCP Periodic",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*gcp.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP - OpenShift 4.9 Azure Periodic",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /.*4.9.*azure.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.8 AWS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*aws.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*aws.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*aws.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.8 GCP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*gcp.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*gcp.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*gcp.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.8 Azure",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*azure.*/  AND \"state\" = 'success' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*azure.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*4.8.*azure.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP -  OpenShift 4.8 AWS Periodic",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\",  \"duration\",   \"build_id\", \"log\" FROM \"build\" WHERE (\"job_name\" =~ /^periodic.*4.8.*aws.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP -  OpenShift 4.8 GCP Periodic",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\",  \"duration\",   \"build_id\", \"log\" FROM \"build\" WHERE (\"job_name\" =~ /^periodic.*4.8.*gcp.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP -  OpenShift 4.8 Azure Periodic",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\",  \"duration\",   \"build_id\", \"log\" FROM \"build\" WHERE (\"job_name\" =~ /^periodic.*4.8.*azure.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.7 AWS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*aws.*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*aws.*/  AND \"state_int\"= 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*aws.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.7 GCP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 84 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*gcp.*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*gcp.*/  AND \"state_int\"= 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*gcp.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.7 Azure",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 84 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*.azure*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*.azure*/  AND \"state_int\"= 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*4.7.*azure.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP -  OpenShift 4.7 AWS Periodic",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\",  \"duration\",   \"build_id\", \"log\" FROM \"build\" WHERE (\"job_name\" =~ /^periodic.*4.7.*aws.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP -  OpenShift 4.7 GCP Periodic",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\",  \"duration\",   \"build_id\", \"log\" FROM \"build\" WHERE (\"job_name\" =~ /^periodic.*4.7.*gcp.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OADP -  OpenShift 4.7 Azure Periodic",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\",  \"duration\",   \"build_id\", \"log\" FROM \"build\" WHERE (\"job_name\" =~ /^periodic.*4.7.*azure.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}