{
 "title": "Pelorus Pull Request",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OpenShift 4.10 Pelorus Unit Test",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*pelorus-master-4.10.*unit.*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*pelorus-master-4.10.*unit*/  AND \"state_int\" = 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*pelorus-master-4.10.*unit.*/  AND \"state_int\" = 3 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FLAKE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*.*pelorus-master-4.10.*unit.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.10 Pelorus E2E Test",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^pull.*pelorus.*4.10.*e2e.*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.10.*e2e.*/  AND \"state_int\" = 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.10.*e2e.*/  AND \"state_int\" = 3 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FLAKE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.10.*e2e.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Executions",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"autogen\".\"build\" WHERE (\"job_name\" =~ /^pull.*pelorus.*/) AND $timeFilter GROUP BY \"job_name\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.9 Pelorus Unit Test",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*pelorus-master-4.9.*unit.*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*pelorus-master-4.9.*unit*/  AND \"state_int\" = 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*pelorus-master-4.9.*unit.*/  AND \"state_int\" = 3 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FLAKE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*.*pelorus-master-4.9.*unit.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.9 Pelorus E2E Test",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^pull.*pelorus.*4.9.*e2e.*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.9.*e2e.*/  AND \"state_int\" = 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.9.*e2e.*/  AND \"state_int\" = 3 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FLAKE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.9.*e2e.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pelorus End to End ( E2E ) Pass / Fail Rate ",
   "type": "table",
   "gridPos": { "h": 17, "w": 11, "x": 12, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"state_int\") as \"passed\"  FROM \"build\" WHERE (\"job_name\" =~ /^pull.*pelorus-master.*.e2e.*/ and \"state_int\" = 0 ) GROUP BY pull_request\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"state_int\") as \"failed\"  FROM \"build\" WHERE (\"job_name\" =~ /^pull.*pelorus-master.*.e2e.*/ and \"state_int\" = 2) GROUP BY pull_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"state_int\") as \"aborted\"  FROM \"build\" WHERE (\"job_name\" =~ /^pull.*pelorus-master.*.e2e.*/ and \"state_int\" = 3) GROUP BY pull_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"state_int\") as \"flake\"  FROM \"build\" WHERE (\"job_name\" =~ /^pull.*pelorus-master.*.e2e.*/ and \"state_int\" = 4) GROUP BY pull_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.8 Pelorus Unit Test",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /.*pelorus-master-4.8.*unit.*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*pelorus-master-4.8.*unit*/  AND \"state_int\" = 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*pelorus-master-4.8.*unit.*/  AND \"state_int\" = 3 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FLAKE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /.*pelorus-master-4.8.*unit.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpenShift 4.8 Pelorus E2E Test",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^pull.*pelorus.*4.8.*e2e.*/  AND \"state_int\" = 0 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.8.*e2e.*/  AND \"state_int\" = 2 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ABORTED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.8.*e2e.*/  AND \"state_int\" = 3 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FLAKE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^pull.*pelorus.*4.8.*e2e.*/  AND \"state_int\" = 4 ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pelorus - Upstream - unit",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\",  \"pull_request\", \"duration\",   \"build_id\", \"log\" FROM \"build\" WHERE (\"job_name\" =~ /^pull.*pelorus-master.*unit.*/  ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pelorus - Upstream - e2e",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\", \"state_int\",  \"pull_request\", \"duration\",   \"build_id\", \"log\" FROM \"build\" WHERE (\"job_name\" =~ /^pull.*pelorus-master.*e2e.*/  ) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}