apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
    - name: front
      port: 3000
      targetPort: front
  selector:
    io.kompose.service: grafana
    app: grafana
status:
  loadBalancer: {}
