apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: telegraf
  name: telegraf
  namespace: go-scrape-prow
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: grafana
  name: grafana-sidecar
  namespace: go-scrape-prow
spec: {}

